### ISSUE TITLE
setDirection doesn't work

### ISSUE THREAD

**Issue by michaelprimez** [GwonHyeok/StickySwitch#1]
Hi, 

Pretty nice lib. I try to use the setDirection to initialize the StickySwitch right but for me doesn't work. Do i have to do anything else?
I use setDirectiom(StickySwitcj.Direction.RIGHT)  inside onCreate to initialize it.

Thanks

**Comment by GwonHyeok** [comment]
@michaelprimez 

Thanks for using this library

I think direction variable is changed but animation is not started.
So i'm released new version.
version code : `0.0.5`

Change Log
* Start animation when call setDirection.

Todo
* When using setDirection, we will add the ability to choose whether to animate. 
 
Thanks ! 👍

**Comment by michaelprimez** [comment]
It works now, thanks
