### ISSUE TITLE
Vector drawable support for devices < api 21

### ISSUE THREAD

**Issue by kenshin171** [GwonHyeok/StickySwitch#12]
Please implement a setRghtIcon(Drawable) method (so i can implement a bindingAdapter to solve the vector drawable issue)

~~or better yet support vector drawable as drawable resource Id in xml input by using ContextCompat.getDrawable(context, drawable_id)~~

Update: ContextCompat.getDrawable in custom view class does not work for vector drawables

**Comment by kenshin171** [comment]
I see in version 0.0.11, that internally StickySwitch is using ```ContextCompat.getDrawable(this, drawableId)```

However i was mistaken, this is still not sufficient in supporting inflation of vector drawables. So please implement a ```setRightIcon(Drawable)``` function to support manual setting of vector drawables from a dataBinding ```@BindingAdapter``` or from java code.

**Comment by kenshin171** [comment]
Update: My apologies, after some research i found out that its not ```ContextCompat.getDrawable(this, drawableId)``` not working, its ```typedArray.getDrawable(R.styleable.StickySwitch_ss_leftIcon)``` that is the culprit.

what i did was this in my bindinAdapter
```java
    @BindingAdapter({"app:custom_leftIcon"})
    public static void setLeftIcon(StickySwitch view, Drawable d) {

        view.setLeftIcon(d);
    }

    @BindingAdapter({"app:custom_rightIcon"})
    public static void setRightIcon(StickySwitch view,@DrawableRes int drawableId) {
        
        view.setRightIcon(drawableId);
    }
```

and here is my xml
```xml

<layout>

    <data>
        <import type="com.emken.meow.R"/>
    </data>

 <io.ghyeok.stickyswitch.widget.StickySwitch
                    android:id="@+id/sgLunchDinner"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:ss_iconSize="18dp"
                    app:ss_iconPadding="18dp"
                    app:ss_leftText="Lunch"
                    app:ss_rightText="Dinner"
                    app:ss_selectedTextSize="16sp"
                    app:ss_sliderBackgroundColor="@color/image_window_background"
                    app:ss_switchColor="@color/coloraccent_500"
                    app:ss_textColor="@android:color/black"
                    app:ss_textSize="14sp"
                    app:ss_animationDuration="300"
                    app:layout_constraintTop_toBottomOf="@+id/tvTypeTitle"
                    app:layout_constraintStart_toStartOf="@+id/paddingStartGuideline"
                    app:layout_constraintEnd_toEndOf="@+id/paddingEndGuideline"
                    app:layout_constraintHorizontal_bias="0.0"
                    android:layout_marginTop="16dp"
                    app:custom_leftIcon="@{@drawable/ic_wb_sunny}"
                    app:custom_rightIcon="@{R.drawable.ic_wb_cloudy}"
                    />
</layout>
```

take note of 
``` app:custom_leftIcon="@{@drawable/ic_wb_sunny}"``` 
and 
```app:custom_rightIcon="@{R.drawable.ic_wb_cloudy}" ```

The reason why one is getting a drawable directly and one needs to supply a drawable resource id is because there is no ```setRightIcon(Drawable d)``` function

**Comment by coolmyll** [comment]
I have the same problem. Can the dev fix it?

**Comment by GwonHyeok** [comment]
i'm fixed this icon issue
now you can use new release library (version code 0.0.13)
check README.md

@coolmyll @kenshin171
