### ISSUE TITLE
Feature Request: ALlow setting of animation speed

### ISSUE THREAD

**Issue by kenshin171** [GwonHyeok/StickySwitch#13]
Allow setting of switch state change animation e.g. switch.setAnimSpeed(300) or app:animSpeed=300

**Comment by GwonHyeok** [comment]
Thank you for your interest in this library.

0.1.11 release is support custom animation duration.

[support custom animation duration](https://github.com/GwonHyeok/StickySwitch/commit/b1504c1a962f2ad7975d0f551fa43bdfd0ca0418)

more details [README.md](https://github.com/GwonHyeok/StickySwitch/blob/master/README.md)

thank you
