### ISSUE TITLE
java.lang.NullPointerException in fragment

### ISSUE THREAD

**Issue by MohammadAmin94** [GwonHyeok/StickySwitch#14]
Hi,
i want to use that in fragment but in setOnSelectedChangeListener method give this error:
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.ghyeok.stickyswitch.widget.StickySwitch.setOnSelectedChangeListener(io.ghyeok.stickyswitch.widget.StickySwitch$OnSelectedChangeListener)' on a null object reference
plz help to solve error
thanks

**Comment by yousefl0** [comment]
Hi @MohammadAmin94 
Please tell me how you solved this problem

**Comment by GwonHyeok** [comment]
@yousefl0 

Do you have the same problem?
