### ISSUE TITLE
left and right icon does not shown at all!

### ISSUE THREAD

**Issue by BigGitWorld** [GwonHyeok/StickySwitch#18]
Hi
I tried to use svg and png drawable format for left and right icon in dialogFragment.
1. this library does not allow svg icon at all for api<21
2. png icons does not shown too when launch application
why?

**Comment by GwonHyeok** [comment]
#12 i think this is a same issue and now i'm fixed icon issue

now you can use new release library (version code 0.0.13)
check README.md
