### ISSUE TITLE
Enchancement, Animation and selected background size.

### ISSUE THREAD

**Issue by tjouin** [GwonHyeok/StickySwitch#19]
Can it be possible to add the same animation LINE without the fact that the circle reduce his size during animation. Juste have a circle that go left from right and right from left.

Can we have the possibility to set the circle background dimension?

Thanks for the lib she is great and sorry for low english skills :)

PS: I will make a pull request this week if you want !

**Comment by GwonHyeok** [comment]
Thank you for using this library.
I will review it after you request it.

**Comment by tjouin** [comment]
It's currently postponed, but I will do it in the next week.

**Comment by richamadnanigate6** [comment]
I want to make sticky switch with direction of Top to Bottom instead of Left to Right. Is it possible??

**Comment by tjouin** [comment]
You will have to fork and do it yourself.

I will close this because i'am not working anymore with this library. Thanks anyway, good library !
