### ISSUE TITLE
Sticky switch problem

### ISSUE THREAD

**Issue by Ajimi** [GwonHyeok/StickySwitch#2]
I copy and pasted the example below . 

```
 <io.ghyeok.stickyswitch.widget.StickySwitch
        android:id="@+id/sticky_switch"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:iconPadding="18dp"
        app:iconSize="22dp"
        app:leftIcon="@drawable/ic_male"
        app:leftText="Male"
        app:rightIcon="@drawable/ic_female"
        app:rightText="Female"
        app:selectedTextSize="14sp"
        app:sliderBackgroundColor="@color/colorSliderBackground"
        app:switchColor="@color/colorSwitchColor"
        app:textColor="@color/colorTextColor"
        app:textSize="12sp" />
```

I have a Fragment contains a StickySwitch and a viewPager That let me slide between fragments but the problem is both are not the same width.
![17343051_10206794118212090_8869343590093681844_n](https://cloud.githubusercontent.com/assets/9468146/24099234/6daf7478-0d6e-11e7-8726-934a93df64f1.jpg)
![17362850_10206794118452096_4568935870435814851_n](https://cloud.githubusercontent.com/assets/9468146/24099236/6f49d8c8-0d6e-11e7-87b7-88b42a6b07a3.jpg)

You can mention the difference between two layouts is it a bug or should I add more parameters ?

**Comment by GwonHyeok** [comment]
I haven't found the cause yet.
I think the temporary solution is change "wrap_content" to fixed value like dp

For example )
```android:layout_width="150dp"```

I will update the issue as soon as possible.

Thanks you 😊

**Comment by Ajimi** [comment]
Thanks for responding I wish that I knew how to develop in Kotlin in order to help you
