### ISSUE TITLE
how to set switch clickable false?

### ISSUE THREAD

**Issue by DLeague9** [GwonHyeok/StickySwitch#21]
i want to set switch clickable false but nothing is working i tried everything.
` stickyswitch.setEnabled(false);
  stickyswitch.setClickable(false);`

**Comment by GwonHyeok** [comment]
@DLeague9 

[Implement clickable](https://github.com/GwonHyeok/StickySwitch/commit/a2bcd7b56a5ca6c377d5a31ca424b0fa27ec0970)

today i will update library
version name is 0.0.14

thank you
