### ISSUE TITLE
Access to IconSize and other functions

### ISSUE THREAD

**Issue by ghost** [GwonHyeok/StickySwitch#29]
Are there ways to access the other ss_ member variables like IconSize as I would like to set them using Anko layouts, however, I run into the val cannot be reassigned error

**Comment by adrielcafe** [comment]
@lancepillar12 check my fork, I added custom setters for iconSize and iconPadding properties.
https://github.com/adrielcafe/StickySwitch

@GwonHyeok I created a PR with my changes, #30
