### ISSUE TITLE
Setter And getter

### ISSUE THREAD

**Issue by Ajimi** [GwonHyeok/StickySwitch#3]
- LeftIcon
- RightIcon
- SliderBackgroundColor
- SwitchColor
- BackgroundColor

**Comment by GwonHyeok** [comment]
thanks for reporting the issue
Now the functions are working!! 😲

[commit - implements more get, set property](https://github.com/GwonHyeok/StickySwitch/commit/5142bb1b8a82453b53da02930954a6b4272f2d0f)

**Comment by Ajimi** [comment]
Woow Quick Response thank you :1st_place_medal:
