### ISSUE TITLE
The height and width are not adjusted.

### ISSUE THREAD

**Issue by KwonDoby** [GwonHyeok/StickySwitch#31]
Hello, I'm trying to adjust the height and width, but the view is cut off and it doesn't shrink. How do I adjust the height and width?

안녕하세요. 높이와 너비를 조절하려고하는데 뷰가 잘리기만 하고 실제로는 줄어 들지 않습니다. 높이와 너비를 조절 하려면 어떻게 해야하나요?

**Comment by GwonHyeok** [comment]
@KwonDoby

#27 해당 이슈 확인해보시면 될 것 같습니다.
