### ISSUE TITLE
Manifest Merger Failed

### ISSUE THREAD

**Issue by yasinhajilou** [GwonHyeok/StickySwitch#32]
after I implemented this library i recieved this error 
_

> ERROR: Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:12:9-36
> 	is also present at [com.github.GwonHyeok:StickySwitch:0.0.15] AndroidManifest.xml:12:9-35 value=(true).
> 	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:10:5-29:19 to override.

_
can you remove allowbackup  attribute?

**Comment by GwonHyeok** [comment]
Hello @yasinhajiloo 

now i'm check that issue and i will update soon.

update version will be changed manifest merge issue and migrate to android x 

thanks for using my library

👍

**Comment by GwonHyeok** [comment]
now released 0.0.16 
thanks

**Comment by yasinhajilou** [comment]
Hello , Thank u for your quick response.
