### ISSUE TITLE
Please prefix attrs with component name

### ISSUE THREAD

**Issue by wezley98** [GwonHyeok/StickySwitch#6]
Please can you add a namespace to your attributes. app:textcolor is not unique and causes clashes with other components. eg app:sticky_textcolor

I am currently getting clashes with https://github.com/mancj/MaterialSearchBar when compiling with the following error Error:(449) Attribute "textColor" already defined with incompatible format.

I have posted the same issue against the other component.

**Comment by mohamadhadibi** [comment]
I have this issue with textSize too.
Error:(410) Attribute "textSize" already defined with incompatible format.

**Comment by islavstan** [comment]
Error:(952) Attribute "textSize" already defined with incompatible format.
Error:(952) Attribute "textColor" already defined with incompatible format.

**Comment by GwonHyeok** [comment]
[commit - Please prefix attrs with component name](https://github.com/GwonHyeok/StickySwitch/commit/d7ad865f747f7234873247dddd85cc555c33896f)

I'm sorry that the update was delayed.
now i'm added a prefix now, so we will upload the next version soon.
