### ISSUE TITLE
setDirection function with animation

### ISSUE THREAD

**Issue by huy-lv** [GwonHyeok/StickySwitch#9]
Your project is awesome, pls add the setDirection(direction,boolean animate) allow dev decide animate or not. Thank you!

**Comment by GwonHyeok** [comment]
[support toggle animate in setDirection method](https://github.com/GwonHyeok/StickySwitch/commit/88c33bf3e52c3c11358787791c9b1c0ca0b9cb9e)

[setDirection without animation](https://github.com/GwonHyeok/StickySwitch/commit/418060cab126a25973fb854e07f56285909201a3)
